services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    environment:
      PUID: 993     # filebrowser
      PGID: 1003    # cloud
      UMASK: "002"  # grant group write access
    ports:
      - "8001:80"
    volumes:
      - /mnt/alexandria/cloud:/srv
      - /mnt/alexandria/appdata/filebrowser/database:/database
      - /mnt/alexandria/appdata/filebrowser/config:/config
    networks:
      - elofyra

networks:
  elofyra:
    external: true
