services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    user: "989:1004"  # portainer:elofyra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/alexandria/appdata/portainer:/data
    ports:
      - 9000:9000
      - 9443:9443
    networks:
      - elofyra

networks:
  elofyra:
    external: true
